export const icons = {
  "alert-info": require("./alert-info.png"),
  "at-sign": require("./at-sign.png"),
  attach: require("./attach.png"),
  "back-arrow": require("./back-arrow.png"),
  back: require("./back.png"),
  check: require("./check.png"),
  search: require("./search.png"),
  microphone: require("./microphone.png"),
  tag: require("./tag.png"),
  close: require("./close.png"),
  heart: require("./heart.png"),
  menu: require("./menu.png"),
  "arrow-left": require("./arrow-left.png"),
  "forward-arrow": require("./forward-arrow.png"),
  export: require("./export.png"),
  external: require("./external.png"),
  edit: require("./edit.png"),
  plus: require("./plus.png"),
  "chart-pie": require("./chart-pie.png"),
  star: require("./star.png"),
  copy: require("./copy.png"),
  twitter: require("./twitter.png"),
  instagram: require("./instagram.png"),
  link: require("./link.png"),
};

export type IconTypes = keyof typeof icons;
