export const icons = {
  "alert-info": require("./alert-info.png"),
  "at-sign": require("./at-sign.png"),
  attach: require("./attach.png"),
  "back-arrow": require("./back-arrow.png"),
  back: require("./back.png"),
  check: require("./check.png"),
  search: require("./search.png"),
  microphone: require("./microphone.png"),
  mail: require("./mail.png"),
  tag: require("./tag.png"),
  close: require("./close.png"),
  heart: require("./heart.png"),
  menu: require("./menu.png"),
  "arrow-left": require("./arrow-left.png"),
  "forward-arrow": require("./forward-arrow.png"),
  export: require("./export.png"),
  external: require("./external.png"),
  edit: require("./edit.png"),
  plus: require("./plus.png"),
  "chart-pie": require("./chart-pie.png"),
  star: require("./star.png"),
  copy: require("./copy.png"),
  twitter: require("./twitter.png"),
  "twitter-primary": require("./twitter-primary.png"),
  instagram: require("./instagram.png"),
  "instagram-primary": require("./instagram-primary.png"),
  link: require("./link.png"),
  "link-primary": require("./link-primary.png"),
  "facebook-primary": require("./facebook-primary.png"),
  "discord-primary": require("./discord-primary.png"),
  "tiktok-primary": require("./tiktok-primary.png"),
  "youtube-fill-primary": require("./youtube-fill-primary.png"),
  more: require("./more.png"),
  cut: require("./cut.png"),
  image: require("./image.png"),
  card: require("./card.png"),
  call: require("./call.png"),
  people: require("./people.png"),
  wallet: require("./wallet.png"),
  hide: require("./hide.png"),
  scroll: require("./scroll.png"),
};

export type IconTypes = keyof typeof icons;
